### ISSUE TITLE
options (e.g class property) in active form can not be set

### ISSUE THREAD

**Issue by omidgh88** [MrMiM/yii2-jdate#12]
in regular set i can set html class propert like this :
`<?= jDate\DatePicker::widget([
    'name' => 'datepicker',
    'options' => [
        'class' => 'form-control',
    ]
]) ?>`
but in active form cant :
`<?= $form->field($model, 'bc_date')->widget(jDate\DatePicker::className([
        'options' => [
            'class' => 'form-control',
        ]
    ])) ?>`
any advice?

**Comment by thinker-amir** [comment]
@omidgh88 
you can use option, see sample code
```
<?= $form->field($model, 'expire_date')->widget(
            Datepicker::className(), [
            'options' => ['class'=>'form-control'],
]); ?>
```

**Comment by omidgh88** [comment]
Thanks a lot.
