### ISSUE TITLE
how to configure the values between db and view?

### ISSUE THREAD

**Issue by p3ym4n** [MrMiM/yii2-jdate#4]
hi , first of all thanks for this widget .
but after all i cant find any method or property for changing model property value from timestamp to time like yyyy/MM/dd . if i'm going wrong please tell me.
also nothing for the reverse like mktime() or something.. for changing the date picker value into timestamp .
thanks.

**Comment by MrMiM** [comment]
Are you need something like this answer?

In first parameter you should send date form like Y-m-d H:i:s and if you want convert date , use strtotime function then send that as seconde parameter.

Like It:

$this->jdate->date('Y-m-d H:i:s', strtotime($yourTimeFromDb);
